/** Instanced particle presets, bursts, foliage drift, fireflies, pollen and motes. */

import { effectsState } from "../state.js";
export function createWaterParticlePresets() {
  return {
    splash: {
      count: 16,
      sprite: [
        effectsState.fxSpriteKinds.DROP,
        effectsState.fxSpriteKinds.DROP,
        effectsState.fxSpriteKinds.DOT,
      ],
      colors: [
        [0.75, 0.92, 1],
        [0.9, 0.97, 1],
        [0.55, 0.85, 1],
      ],
      size: [0.12, 0.22],
      sizeEnd: 0.6,
      life: [0.5, 0.85],
      speed: [0.8, 2.2],
      up: [3.2, 5.5],
      spread: 0.25,
      gravity: 13,
      drag: 0.4,
      spin: [0, 0],
      alpha: 0.95,
      add: 0,
      emis: 0.35,
      sway: 0,
    },
    bubbles: {
      count: 6,
      sprite: [effectsState.fxSpriteKinds.RING],
      colors: [[0.8, 0.95, 1]],
      size: [0.1, 0.2],
      sizeEnd: 1.2,
      life: [1.2, 2],
      speed: [0.1, 0.4],
      up: [0.8, 1.4],
      spread: 0.3,
      gravity: -0.6,
      drag: 1.5,
      spin: [0, 0],
      alpha: 0.8,
      add: 0.3,
      emis: 0.5,
      sway: 0.08,
      swayF: 5,
    },
    ripple: {
      count: 1,
      sprite: [effectsState.fxSpriteKinds.RING],
      colors: [[0.85, 0.95, 1]],
      size: [0.5, 0.7],
      sizeEnd: 4,
      life: [0.8, 1.1],
      speed: [0, 0],
      up: [0, 0],
      spread: 0.15,
      stagger: 0.18,
      gravity: 0,
      drag: 1,
      spin: [0, 0],
      alpha: 0.55,
      add: 0.4,
      emis: 0.6,
      sway: 0,
      flat: 1,
    },
  };
}
