/** Shared props data. Initialized explicitly before the game systems start. */
export const propsState = {
  propTextureWorldSizes: undefined,
  propTransformQuaternion: undefined,
  propTransformEuler: undefined,
  propTransformScale: undefined,
  propTransformPosition: undefined,
  propVertexColorScratch: undefined,
  propMaterialCache: undefined,
  propPalette: undefined,
  propFullTurn: undefined,
  buildingFullTurn: undefined,
  ivyLeafGeometryCache: undefined,
  ivyLeafPalette: undefined,
  cottageVariants: undefined,
  flatLeafGeometryCache: undefined,
  smokeParticleTextureCache: undefined,
  glowParticleTextureCache: undefined,
  flameParticleTextureCache: undefined,
  propBillboardVertexShader: undefined,
  propBillboardFragmentShader: undefined,
  propDecalVertexShader: undefined,
  propDecalFragmentShader: undefined,
  campfireVertexShader: undefined,
  campfireFragmentShader: undefined,
  windmillFrontOffset: undefined,
  propsSystem: undefined,
  propsRuntime: undefined,
  propColliders: undefined,
  propEntries: undefined,
  propVegetationClearings: undefined,
  propsFallbackCameraPosition: undefined,
  propsApi: undefined,
};
