export const SHELLHAVEN_PLACES = [
  {
    id: "shellhaven-gate",
    name: "Shellhaven Gate",
    x: 6,
    z: 55,
    icon: "☀",
    note: "Follow the pale sandy walk south toward Shell Cove.",
  },
  {
    id: "shell-cove",
    name: "Shell Cove",
    x: -16,
    z: 78,
    icon: "❋",
    note: "Six colorful shells wait along the coast. Look for small sparkles, walk close, and open J to collect them. Your display shelf stands just south of the cove.",
  },
  {
    id: "tidepool-garden",
    name: "Tidepool Garden",
    x: -39,
    z: 91,
    icon: "≈",
    note: "Circle the little tide pool, and look for shells on its dry coastal paths.",
  },
  {
    id: "seabreeze-bluff",
    name: "Seabreeze Bluff",
    x: 17,
    z: 90,
    icon: "△",
    note: "Look back across the sandy coves from the grassy bluff. The sunset makes a lovely keepsake.",
  },
  {
    id: "driftwood-camp",
    name: "Driftwood Camp",
    x: -60,
    z: 73,
    icon: "☆",
    note: "Rest beside the coastal camp, then search the southern sand walk for a seafoam shell.",
  },
];

export const DISPLAY_SHELF = { x: -16, z: 82 };
export const COAST_SHELLS = [
  {
    id: "coral-fan",
    name: "Coral Fan",
    x: -8,
    z: 72,
    color: 0xed9689,
    shape: "fan",
    hint: "Follow the sandy loop northeast of Shell Cove.",
  },
  {
    id: "moon-pearl",
    name: "Moon Pearl",
    x: -25,
    z: 79,
    color: 0xf5e5bc,
    shape: "pearl",
    hint: "Search along the walk west from Shell Cove.",
  },
  {
    id: "violet-conch",
    name: "Violet Conch",
    x: -34,
    z: 89,
    color: 0xc1a8dc,
    shape: "spiral",
    hint: "Look between the cove path and Tidepool Garden.",
  },
  {
    id: "sunrise-cockle",
    name: "Sunrise Cockle",
    x: -49,
    z: 92,
    color: 0xf0c772,
    shape: "fan",
    hint: "Continue west past Tidepool Garden along the sand walk.",
  },
  {
    id: "seafoam-spiral",
    name: "Seafoam Spiral",
    x: -57,
    z: 78,
    color: 0x9fcabc,
    shape: "spiral",
    hint: "Walk south from Driftwood Camp and watch the pale sand.",
  },
  {
    id: "rose-scallop",
    name: "Rose Scallop",
    x: 7,
    z: 98,
    color: 0xe9a7bd,
    shape: "fan",
    hint: "Take the southern cove loop toward Seabreeze Bluff.",
  },
];
