const pi = Math.PI;
/** Fixed authored replacements: name, approved design, optional revised x/z/rotation. */
export const replacements = [
  ["Sunflower cottage", "gardenkeeper-cottage", 82, -23, 0],
  ["Seabreeze cottage", "conservatory-home", 93.5, 4.5, pi],
  ["Willowmere cabin", "stump-home"],
  ["Driftwood cabin", "boat-roof-home"],
  ["Woodland picnic stand", "stone-tower"],
  ["Picnic fruit stand", "florist-cart"],
  ["Willowmere post", "acorn-mailbox"],
  ["Seabreeze reading bench", "pergola-swing"],
  ["Picnic garden bench", "picnic-pavilion", 71, 17, 0],
  ["Picnic circle bench", "tree-circle-bench", 69, 11, 0],
  ["Firefly camp bench", "fern-scroll-bench"],
  ["Sunrise lookout bench", "reading-seat"],
  ["Ocean lookout bench", "fern-scroll-bench"],
  ["Shellshore bench", "flower-box-bench"],
  ["Willowmere garden bench", "flower-box-bench"],
  ["Lake reading bench", "reading-seat"],
  ["Quietwater reading bench", "fern-scroll-bench"],
  ["Southern lake bench", "reading-seat"],
  ["Woodland gate bench", "flower-box-bench", -10, -55, -pi / 2],
  ["Lanternwood camp bench", "fern-scroll-bench"],
  ["Lantern grove reading bench", "reading-seat"],
  ["Fernridge lake lookout", "reading-seat"],
  ["Fernridge ocean lookout", "fern-scroll-bench"],
  ["Driftwood fireside bench", "fern-scroll-bench"],
  ["Quiet inlet bench", "reading-seat"],
  ["Shell Cove reading bench", "reading-seat"],
  ["Shell Cove shaded bench", "flower-box-bench"],
  ["Shellhaven sunset bench", "flower-box-bench"],
  ["Tidepool watching bench", "fern-scroll-bench"],
  ["Tidepool southern bench", "reading-seat"],
  ["Seabreeze ocean lookout", "reading-seat"],
  ["Seabreeze island lookout", "flower-box-bench"],
  ["Shellhaven arrival bench", "fern-scroll-bench"],
  ["Shellhaven gate lantern", "twin-lantern"],
  ["Shell Cove lantern", "flower-lantern"],
  ["Beach walk lantern", "lily-bell-lamp"],
  ["Bluff trail lantern", "celestial-globe"],
  ["Driftwood camp lantern", "twin-lantern"],
  ["Seaside market lantern", "flower-lantern"],
  ["Tidepool trail lantern", "lily-bell-lamp"],
  ["Driftwood trail lantern", "twin-lantern"],
];
/** Existing unnamed street lights have fixed coordinates in the district source. */
export const streetLights = [
  [44, -5, "twin-lantern"],
  [57, 4, "twin-lantern"],
  [69, 7, "flower-lantern"],
  [82, 3, "lily-bell-lamp"],
  [89, -5, "flower-lantern"],
  [99, -18, "celestial-globe"],
  [73, 20, "lily-bell-lamp"],
  [83, 18, "flower-lantern"],
  [98, 24, "twin-lantern"],
  [66, -18, "mushroom-lantern"],
  [64, -28, "celestial-globe"],
  [-8, -47, "mushroom-lantern"],
  [-20, -58, "mushroom-lantern"],
  [-28, -62, "mushroom-lantern"],
  [-4, -69, "lily-bell-lamp"],
  [12, -73, "mushroom-lantern"],
  [-49, -53, "flower-lantern"],
  [-65, -90, "celestial-globe"],
];
/** New landmarks have permanent identities and coordinates, never scatter/search. */
export const additions = [
  ["sun-windmill", "windmill-neighbour", 71, -10, 0],
  ["sun-glasshouse", "glass-garden-home", 89.5, 25, pi / 2],
  ["willow-mushroom", "mushroom-home", -5, -58, pi],
  ["willow-library", "woodland-library", -34, -58, pi],
  ["sun-rose-gate", "rose-gate", 77, -34, 0],
  ["sun-fountain", "lily-fountain", 86, 13, 0],
];
/** Keep washing lines and supplies beside the larger homes, clear of their entrances. */
export const relocations = [
  ["washingLine", 8.3, 16.8, 11, 18],
  ["barrel", 88, -20, 89, -20],
  ["crateStack", 86.5, 24, 85, 27],
];
