/** Shared player data. Initialized explicitly before the game systems start. */
export const playerState = {
  playerGardenOccluderPattern: undefined,
  playerBuildingOccluderPattern: undefined,
  playerNonSolidBlockPattern: undefined,
  playerMovementSettings: undefined,
  playerCollisionEpsilon: undefined,
  playerWrappedLightingChunk: undefined,
  playerFeltNoiseGlsl: undefined,
  playerStylizedMaterials: undefined,
  playerFadeUniform: undefined,
  playerFadeDeclarationGlsl: undefined,
  playerFadeDiscardGlsl: undefined,
  playerNightTint: undefined,
  playerDayRimColor: undefined,
  playerNightRimColor: undefined,
  playerTintUniform: undefined,
  playerSurfaceNormalScratch: undefined,
  playerForwardAxis: undefined,
  playerPalette: undefined,
  playerGeometryCache: undefined,
  playerKeyBindings: undefined,
  playerPreventDefaultKeys: undefined,
  playerCameraOffsetDirection: undefined,
  playerCameraForwardScratch: undefined,
  playerCameraRightScratch: undefined,
  playerCameraUpScratch: undefined,
  playerSystem: undefined,
  playerPhysicsTimeStep: undefined,
  playerMaxPhysicsSteps: undefined,
  playerRuntime: undefined,
  playerFoliageFadeTarget: undefined,
  playerCreatureLookTarget: undefined,
};
