/** Cottage variants, porch and stair layout, cottage geometry and hanging baskets. */
import { propsState } from "../state.js";
export function preparePropsCottages() {
  propsState.cottageVariants = {
    main: {
      W: 6.2,
      D: 4.8,
      wallH: 2.9,
      walls: `plaster`,
      roof: propsState.propPalette.roofRed,
      door: propsState.propPalette.doorTeal,
      shutter: propsState.propPalette.shutterGreen,
      doorX: -1,
      porch: `gable`,
      chimney: `stone`,
      frontWindows: [1.55],
      frontShutters: true,
      woodpile: true,
      ivy: true,
      baskets: true,
      barrel: true,
      flowers: propsState.propPalette.pink,
      box: propsState.propPalette.woodWarm,
    },
    cabin: {
      W: 5.4,
      D: 4.4,
      wallH: 2.9,
      walls: `wood`,
      roof: propsState.propPalette.roofTeal,
      wallTint: 15913896,
      door: propsState.propPalette.doorRed,
      shutter: propsState.propPalette.shutterBlue,
      doorX: 0,
      porch: `veranda`,
      chimney: `brick`,
      dormer: true,
      frontWindows: [-1.62, 1.62],
      frontShutters: false,
      woodpile: false,
      ivy: false,
      baskets: false,
      barrel: false,
      flowers: 16765514,
      box: 6989784,
      flowerCols: [16765514, 16777215, 16747115],
    },
  };
}
