/** Shared terrain data. Initialized explicitly before the game systems start. */
export const terrainState = {
  terrainTextureLayerIds: undefined,
  terrainBlockIds: undefined,
  terrainBlockDefinitions: undefined,
  terrainBiomeIds: undefined,
  terrainBiomeNames: undefined,
  terrainWaterLevel: undefined,
  terrainPondLandmark: undefined,
  terrainHillLandmark: undefined,
  terrainRiverWaypoints: undefined,
  terrainPathWaypoints: undefined,
  terrainTextureLogicalSize: undefined,
  terrainTexturePixelSize: undefined,
  terrainTexturePixelScale: undefined,
  textureFullTurn: undefined,
  terrainAtlasBumpStrengths: undefined,
  mesherGrassBlockId: undefined,
  mesherPathBlockId: undefined,
  mesherMossEligibleBlockIds: undefined,
  shoreSurfaceBlockHeight: undefined,
  shoreEdgeDrop: undefined,
  shoreEdgeFalloff: undefined,
  pathSurfaceDrop: undefined,
  voxelFaceFrames: undefined,
  voxelAmbientOcclusionLevels: undefined,
  terrainSystem: undefined,
  terrainWorldSize: undefined,
  terrainWorldHeight: undefined,
};
